apiVersion: v1
kind: Service
metadata:
  name: my-plants
spec:
  selector:
    app: my-plants
  ports:
    - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-plants
  labels:
    app: my-plants
spec:
  selector:
    matchLabels:
      app: my-plants
  replicas: 1
  template:
    metadata:
      labels:
        app: my-plants
    spec:
      containers:
        - name: my-plants
          image: mplants
          ports:
            - containerPort: 5000
          env:
            - name: DISABLE_WEB_APP
              value: "false"
